// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// DeviceListerExpansion allows custom methods to be added to
// DeviceLister.
type DeviceListerExpansion interface{}

// DeviceNamespaceListerExpansion allows custom methods to be added to
// DeviceNamespaceLister.
type DeviceNamespaceListerExpansion interface{}
