apiVersion: v1
kind: Pod

metadata:
  name: router
  labels:
    app.kubernetes.io/name: router
    app.kubernetes.io/instance: router

spec:
  containers:
  - name: router
    image: docker.io/tliron/router
    imagePullPolicy: Always
    ports:
    - name: netconf
      containerPort: 830
      protocol: TCP

---

apiVersion: v1
kind: Service

metadata:
  name: router
  labels:
    app.kubernetes.io/name: router
    app.kubernetes.io/instance: router

spec:
  selector:
    app.kubernetes.io/name: router
    app.kubernetes.io/instance: router
  ports:
  - { name: netconf, protocol: TCP, targetPort: 830, port: 830 }
