#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/../../scripts/_env"
. "$HERE/../_env"
. "$ROOT/scripts/_trap"

curl -sL https://github.com/operator-framework/operator-lifecycle-manager/releases/download/v$OLM_VERSION/install.sh | \
bash -s v$OLM_VERSION
