#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/../../scripts/_env"
. "$HERE/../_env"
. "$ROOT/scripts/_trap"

m 'deploying couchdb-operator...'
kubectl create -f https://operatorhub.io/install/couchdb-operator.yaml

m 'waiting for couchdb-operator to start...'
POD=$(kubectl get pods --namespace=olm --selector=app=olm-operator --output=jsonpath={.items[0].metadata.name})
kubectl wait "pods/$POD" --namespace=olm \
	--for=condition=ContainersReady
