// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/tliron/candice/apis/clientset/versioned/typed/candice.puccini.cloud/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeCandiceV1alpha1 struct {
	*testing.Fake
}

func (c *FakeCandiceV1alpha1) Devices(namespace string) v1alpha1.DeviceInterface {
	return &FakeDevices{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeCandiceV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
