// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// DeviceStatusApplyConfiguration represents an declarative configuration of the DeviceStatus type for use
// with apply.
type DeviceStatusApplyConfiguration struct {
	LastError *string `json:"lastError,omitempty"`
}

// DeviceStatusApplyConfiguration constructs an declarative configuration of the DeviceStatus type for use with
// apply.
func DeviceStatus() *DeviceStatusApplyConfiguration {
	return &DeviceStatusApplyConfiguration{}
}

// WithLastError sets the LastError field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastError field is set to the value of the last call.
func (b *DeviceStatusApplyConfiguration) WithLastError(value string) *DeviceStatusApplyConfiguration {
	b.LastError = &value
	return b
}
