// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// DeviceDirectApplyConfiguration represents an declarative configuration of the DeviceDirect type for use
// with apply.
type DeviceDirectApplyConfiguration struct {
	Host *string `json:"host,omitempty"`
}

// DeviceDirectApplyConfiguration constructs an declarative configuration of the DeviceDirect type for use with
// apply.
func DeviceDirect() *DeviceDirectApplyConfiguration {
	return &DeviceDirectApplyConfiguration{}
}

// WithHost sets the Host field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Host field is set to the value of the last call.
func (b *DeviceDirectApplyConfiguration) WithHost(value string) *DeviceDirectApplyConfiguration {
	b.Host = &value
	return b
}
