#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/../../../scripts/_env"
. "$ROOT/scripts/_trap"

kubectl delete --ignore-not-found=true -f "$HERE/../kubernetes/ran.yaml"
kubectl create -f "$HERE/../kubernetes/ran.yaml"
