#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/../../../scripts/_env"
. "$ROOT/scripts/_trap"

kubectl delete -f "$HERE/../kubernetes/ran.yaml" || true
kubectl create -f "$HERE/../kubernetes/ran.yaml"
