#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"
. "$HERE/_trap"

"$HERE/build"

# https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/building_running_and_managing_containers/using_red_hat_universal_base_images_standard_minimal_and_runtimes

BASE_IMAGE=registry.access.redhat.com/ubi8/ubi
# note: ubi-minimal does not have "tar" which is needed for kubectl cp

CONTAINER_ID=$(buildah from "$BASE_IMAGE")

buildah run "$CONTAINER_ID" -- dnf --assumeyes --setopt=tsflags=nodocs install python3 python3-devel openssl-devel gcc

# Installing the PyCA cryptography library requires Rust
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | buildah run "$CONTAINER_ID" -- sh -s -- -y --component rustc
buildah run "$CONTAINER_ID" -- python3 -m pip install \
    setuptools-rust wheel

buildah run "$CONTAINER_ID" -- bash -c ". /root/.cargo/env && python3 -m pip install \
	ruamel.yaml==$RUAMEL_YAML_VERSION \
	ncclient==$NCCLIENT_VERSION \
	ZODB==$ZODB_VERSION \
	requests==$REQUESTS_VERSION"

# Remove PyCA cryptography build dependencies
buildah run "$CONTAINER_ID" -- rm --recursive /root/.cargo
buildah run "$CONTAINER_ID" -- dnf --assumeyes remove python3-devel openssl-devel gcc
buildah run "$CONTAINER_ID" -- dnf --assumeyes clean all

buildah add "$CONTAINER_ID" "$GOPATH/bin/candice-operator" /usr/bin/
buildah add "$CONTAINER_ID" "$GOPATH/bin/candice" /usr/bin/
buildah add "$CONTAINER_ID" "$ROOT/python/candice.py" /usr/local/lib/python3.6/site-packages/

buildah config \
	--entrypoint "/usr/bin/candice-operator" \
	--author Candice \
	--created-by buildah \
	"$CONTAINER_ID"

buildah commit "$CONTAINER_ID" localhost/candice-operator
