#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"

gofmt -w -s -e \
	"$ROOT/candice" \
	"$ROOT/candice/commands" \
	"$ROOT/candice-operator" \
	"$ROOT/client" \
	"$ROOT/controller" \
	"$ROOT/resources" \
	"$ROOT/resources/candice.cloud" \
	"$ROOT/resources/candice.cloud/v1alpha1"
