#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/../scripts/_env"
. "$HERE/_env"
. "$ROOT/scripts/_trap"

NAMESPACE=${NAMESPACE:-mynamespace}

m 'cleaning up...'

kubectl create namespace "$NAMESPACE" || true
kubectl config set-context --current --namespace="$NAMESPACE"

candice operator uninstall --wait -v
kubectl delete events --all

if [ "$1" == '-b' ]; then
	"$ROOT/scripts/build-container-image"
	"$ROOT/scripts/publish-container-image"
fi

m 'installing operator...'

candice operator install --wait -v

m 'router device...'

candice device create router --host router.mynamespace.svc.cluster.local:830
candice task set router debug --file="$ROOT/examples/router/tasks/debug.py"
candice task set router about --file="$ROOT/examples/router/tasks/about.py"
candice task set router set-hostname --file="$ROOT/examples/router/tasks/set_hostname.py"
candice task set router set-ip --file="$ROOT/examples/router/tasks/set_ip.py"

candice task run router set-hostname --input=hostname=myhost
candice task run router about --input=message="hello world"

# https://github.com/clicon/clixon
# flex bison
