// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	versioned "github.com/tliron/candice/apis/clientset/versioned"
	internalinterfaces "github.com/tliron/candice/apis/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/tliron/candice/apis/listers/candice.puccini.cloud/v1alpha1"
	candicepuccinicloudv1alpha1 "github.com/tliron/candice/resources/candice.puccini.cloud/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// DeviceInformer provides access to a shared informer and lister for
// Devices.
type DeviceInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.DeviceLister
}

type deviceInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewDeviceInformer constructs a new informer for Device type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewDeviceInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredDeviceInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredDeviceInformer constructs a new informer for Device type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredDeviceInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CandiceV1alpha1().Devices(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CandiceV1alpha1().Devices(namespace).Watch(context.TODO(), options)
			},
		},
		&candicepuccinicloudv1alpha1.Device{},
		resyncPeriod,
		indexers,
	)
}

func (f *deviceInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredDeviceInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *deviceInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&candicepuccinicloudv1alpha1.Device{}, f.defaultInformer)
}

func (f *deviceInformer) Lister() v1alpha1.DeviceLister {
	return v1alpha1.NewDeviceLister(f.Informer().GetIndexer())
}
